package com.dgapr.typeUtilisateur;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/typeUtilisateur") // This means URL's start with /demo (after Application path)
public class TypeUtilisateurController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private TypeUtilisateurRepository typeUtilisateurRepository;

  

  @GetMapping(path="/all")
  public @ResponseBody Iterable<TypeUtilisateur> getAllTypeUtilisateur() {
    // This returns a JSON or XML with the users
    return typeUtilisateurRepository.findAll();
  }
}