package com.dgapr.typeStatus;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/typeStatus") // This means URL's start with /demo (after Application path)
public class TypeStatusController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private TypeStatusRepository typeStatusRepository;

  @GetMapping(path="/id")
  public @ResponseBody Optional<TypeStatus> findById(@PathVariable int Id) {
    // This returns a JSON or XML with the users
    return typeStatusRepository.findById(Id);
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<TypeStatus> getAllTypeStatus() {
    // This returns a JSON or XML with the users
    return typeStatusRepository.findAll();
  }
}