package com.dgapr.panier;

import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.dgapr.typeStatus.TypeStatus;

@RestController
@CrossOrigin(origins = "http://localhost:3000")
@Controller // This means that this class is a Controller
@RequestMapping(path = "/panier") // This means URL's start with /demo (after Application path)
public class PanierController {
  @Autowired // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private PanierRepository panierRepository;

  @Autowired
  private PanierService panierService;

  @GetMapping(path = "/all")
  public @ResponseBody Iterable<Panier> getAllPanier() {
    // This returns a JSON or XML with the users
    return panierRepository.findAll();
  }

  @PostMapping(value = "/order/{totalPrice}", produces = MediaType.APPLICATION_JSON_VALUE)
  public @ResponseBody void save(@PathVariable(value = "totalPrice") Double totalPrice) {
    Panier panier = panierService.createOrGetPanier();
    panier.setTypeStatus(new TypeStatus(1));
    panier.setPrixtotal(totalPrice);
    panierRepository.save(panier);
  }
}